//Fetching flowers
export const FETCH_FLOWERS_BEGIN = "FETCH_FLOWERS_BEGIN";
export const FETCH_FLOWERS_SUCCESS = "FETCH_FLOWERS_SUCCESS";
export const FETCH_FLOWERS_ERROR = "FETCH_FLOWERS_ERROR";

// USER REGISTRATION
export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
